/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Canyon.orders;

import Canyon.tables.SeatView;

/**
 *
 * @author macdonny
 */
public class OrderView extends javax.swing.JFrame {
    
    Order selectedItemOrder;

    /**
     * Creates new form Order
     */
    public OrderView(Order seatOrder) {
        selectedItemOrder = seatOrder;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    OrderView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        appetizersButton = new javax.swing.JButton();
        entreesButton = new javax.swing.JButton();
        sideItemsButton = new javax.swing.JButton();
        dessertButton = new javax.swing.JButton();
        liquorButton = new javax.swing.JButton();
        beersButton = new javax.swing.JButton();
        winesButton = new javax.swing.JButton();
        mixedDrinkButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 700));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 107, 135));
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 700));
        jPanel1.setSize(new java.awt.Dimension(960, 700));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Order");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        appetizersButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        appetizersButton.setText("Appetizer");
        appetizersButton.setMaximumSize(new java.awt.Dimension(300, 125));
        appetizersButton.setMinimumSize(new java.awt.Dimension(300, 125));
        appetizersButton.setPreferredSize(new java.awt.Dimension(300, 125));
        appetizersButton.setSize(new java.awt.Dimension(300, 125));
        appetizersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appetizersButtonActionPerformed(evt);
            }
        });

        entreesButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entreesButton.setText("Entree");
        entreesButton.setMaximumSize(new java.awt.Dimension(300, 125));
        entreesButton.setMinimumSize(new java.awt.Dimension(300, 125));
        entreesButton.setPreferredSize(new java.awt.Dimension(300, 125));
        entreesButton.setSize(new java.awt.Dimension(300, 125));
        entreesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreesButtonActionPerformed(evt);
            }
        });

        sideItemsButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sideItemsButton.setText("Side Item");
        sideItemsButton.setMaximumSize(new java.awt.Dimension(300, 125));
        sideItemsButton.setMinimumSize(new java.awt.Dimension(300, 125));
        sideItemsButton.setPreferredSize(new java.awt.Dimension(300, 125));
        sideItemsButton.setSize(new java.awt.Dimension(300, 125));
        sideItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideItemsButtonActionPerformed(evt);
            }
        });

        dessertButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dessertButton.setText("Dessert");
        dessertButton.setMaximumSize(new java.awt.Dimension(300, 125));
        dessertButton.setMinimumSize(new java.awt.Dimension(300, 125));
        dessertButton.setPreferredSize(new java.awt.Dimension(300, 125));
        dessertButton.setSize(new java.awt.Dimension(300, 125));
        dessertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessertButtonActionPerformed(evt);
            }
        });

        liquorButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        liquorButton.setText("Liquor");
        liquorButton.setMaximumSize(new java.awt.Dimension(300, 125));
        liquorButton.setMinimumSize(new java.awt.Dimension(300, 125));
        liquorButton.setPreferredSize(new java.awt.Dimension(300, 125));
        liquorButton.setSize(new java.awt.Dimension(300, 125));
        liquorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liquorButtonActionPerformed(evt);
            }
        });

        beersButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        beersButton.setText("Beer");
        beersButton.setMaximumSize(new java.awt.Dimension(300, 125));
        beersButton.setMinimumSize(new java.awt.Dimension(300, 125));
        beersButton.setPreferredSize(new java.awt.Dimension(300, 125));
        beersButton.setSize(new java.awt.Dimension(300, 125));
        beersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beersButtonActionPerformed(evt);
            }
        });

        winesButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        winesButton.setText("Wine");
        winesButton.setMaximumSize(new java.awt.Dimension(300, 125));
        winesButton.setMinimumSize(new java.awt.Dimension(300, 125));
        winesButton.setPreferredSize(new java.awt.Dimension(300, 125));
        winesButton.setSize(new java.awt.Dimension(300, 125));
        winesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winesButtonActionPerformed(evt);
            }
        });

        mixedDrinkButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mixedDrinkButton.setText("Mixed Drink");
        mixedDrinkButton.setMaximumSize(new java.awt.Dimension(300, 125));
        mixedDrinkButton.setMinimumSize(new java.awt.Dimension(300, 125));
        mixedDrinkButton.setPreferredSize(new java.awt.Dimension(300, 125));
        mixedDrinkButton.setSize(new java.awt.Dimension(300, 125));
        mixedDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixedDrinkButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous Screen");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(444, 444, 444))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(entreesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(appetizersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sideItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dessertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(winesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(beersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(liquorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mixedDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appetizersButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liquorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entreesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beersButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sideItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(winesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dessertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mixedDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        this.setVisible(false);
        SeatView seatView = new SeatView(selectedItemOrder);
        seatView.setVisible(true);
    }//GEN-LAST:event_previousButtonActionPerformed

    private void appetizersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appetizersButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SelectedItemView selectedItemView = new SelectedItemView(appetizersButton.getText().toLowerCase(), selectedItemOrder);
        selectedItemView.setVisible(true);
    }//GEN-LAST:event_appetizersButtonActionPerformed

    private void entreesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreesButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SelectedItemView selectedItemView = new SelectedItemView(entreesButton.getText().toLowerCase(), selectedItemOrder);
        selectedItemView.setVisible(true);
    }//GEN-LAST:event_entreesButtonActionPerformed

    private void sideItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideItemsButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SelectedItemView selectedItemView = new SelectedItemView(sideItemsButton.getText().toLowerCase(), selectedItemOrder);
        selectedItemView.setVisible(true);
    }//GEN-LAST:event_sideItemsButtonActionPerformed

    private void dessertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessertButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SelectedItemView selectedItemView = new SelectedItemView(dessertButton.getText().toLowerCase(), selectedItemOrder);
        selectedItemView.setVisible(true);
    }//GEN-LAST:event_dessertButtonActionPerformed

    private void liquorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liquorButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SelectedItemView selectedItemView = new SelectedItemView(liquorButton.getText().toLowerCase(), selectedItemOrder);
        selectedItemView.setVisible(true);
    }//GEN-LAST:event_liquorButtonActionPerformed

    private void beersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beersButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SelectedItemView selectedItemView = new SelectedItemView(beersButton.getText().toLowerCase(), selectedItemOrder);
        selectedItemView.setVisible(true);
    }//GEN-LAST:event_beersButtonActionPerformed

    private void winesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winesButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SelectedItemView selectedItemView = new SelectedItemView(winesButton.getText().toLowerCase(), selectedItemOrder);
        selectedItemView.setVisible(true);
    }//GEN-LAST:event_winesButtonActionPerformed

    private void mixedDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixedDrinkButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SelectedItemView selectedItemView = new SelectedItemView(mixedDrinkButton.getText().toLowerCase(), selectedItemOrder);
        selectedItemView.setVisible(true);
    }//GEN-LAST:event_mixedDrinkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appetizersButton;
    private javax.swing.JButton beersButton;
    private javax.swing.JButton dessertButton;
    private javax.swing.JButton entreesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton liquorButton;
    private javax.swing.JButton mixedDrinkButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton sideItemsButton;
    private javax.swing.JButton winesButton;
    // End of variables declaration//GEN-END:variables
}
