package Canyon;
/*
This is the main class to initiate the program, since the screen since after login
depends on the user's access. For example, being a manager would bring up the manager
screen as an option (or just the normal table display), and a host and server
would not see the manager options.
 */
import Canyon.db.tables.EmployeesTable;
import Canyon.managers.ManagerWindow;
import java.util.ArrayList;

public class Login extends javax.swing.JFrame {
    
    EmployeesTable employeesTable;
    boolean login = false;
      
    public Login() {
        employeesTable = EmployeesTable.getInstance();
        initComponents();
        invalidText.setVisible(false);
    }
    // At least a manager has to exist in the database from the outset, so
    // he or she can log in and create more employees. I used "1" as the first and
    // last names, the username, the password, the position rank (1 = Manager), then
    // $20/hour. 
    // Even with just one character name/password, I still get the cursor error.
    
    // NOTE: to make things easier, we should have our servers earn an hourly wage,
    // like European restaurants. That way we don't have to calculate tips for
    // Paychecks.
    
    
   public void addInitialEmployees () {
        // FirstName, LastName, Username, Password, Position, Hourly Wage
        // Manager = 1, Waiter = 2, Host = 3
        employeesTable.AddEmployee("root", "toor", "root", "root", 1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        invalidText = new javax.swing.JLabel();
        loginText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        userField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userField.setForeground(new java.awt.Color(153, 153, 153));
        userField.setText("Username");
        userField.setBorder(null);
        userField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userField.setMargin(new java.awt.Insets(2, 5, 2, 2));
        userField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearUsernameText(evt);
            }
        });

        passField.setForeground(new java.awt.Color(153, 153, 153));
        passField.setText("Password");
        passField.setBorder(null);
        passField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearPasswordText(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passFieldMouseEntered(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(204, 204, 204));
        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginActionViaClick(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        invalidText.setForeground(new java.awt.Color(255, 102, 102));
        invalidText.setText("Invalid login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(invalidText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(passField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        loginText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        loginText.setForeground(new java.awt.Color(204, 204, 204));
        loginText.setText("Canyon Point of Sale System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginText)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(loginText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username =  userField.getText();
        String password =  passField.getText();
        System.out.println(employeesTable.ViewEmployee("1"));

        // Checks to see if the username is in database
        if (employeesTable.VerifyLogin(username)) {
            if (password.equals(employeesTable.ViewEmployee(username).get(3))) {
                this.login = true;
                invalidText.setVisible(false);
                
                // If the user is a manager, load the manager window
                if (Integer.parseInt(employeesTable.ViewEmployee(username).get(4)) == 1) {
                    System.out.println("Manager Login");
                    ManagerWindow mW = new ManagerWindow();
                    mW.setVisible(true);
                } else if (Integer.parseInt(employeesTable.ViewEmployee(username).get(4)) == 2) {
                    System.out.println("Server Login");
                    // Server JFrame would now open
                    //ADD: If Chef
                    //ADD: If Host
                    // Need to create Host and Chef JFrames
                }
            } else {
                invalidText.setText("Invalid Username or Password combination");
                invalidText.setVisible(true);
            }
            setVisible(false);
        } else {
            invalidText.setText("Username not found");
            invalidText.setVisible(true);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void ClearUsernameText(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearUsernameText
        // TODO add your handling code here:
        if (userField.getText().equals("Username")) {
            userField.setText("");
        }
        
        if (passField.getText().equals("")) {
            passField.setText("Password");
        }
    }//GEN-LAST:event_ClearUsernameText

    private void clearPasswordText(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearPasswordText
        // TODO add your handling code here:
        if (passField.getText().equals("Password")) {
            passField.setText("");
        }
        
        if (userField.getText().equals("")) {
            userField.setText("Username");
        }
    }//GEN-LAST:event_clearPasswordText

    private void passFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passFieldMouseEntered
        // TODO add your handling code here:
        passField.setText("********");
    }//GEN-LAST:event_passFieldMouseEntered

    private void LoginActionViaClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginActionViaClick
        // TODO add your handling code here:
         // This is the same code as above. The above code I think would be for
        // when a user hits the return key, and this code is for clicking the button.
         String username =  userField.getText();
        String password =  passField.getText();
        
        System.out.println(employeesTable.ViewEmployee("1"));

        // Checks to see if the username is in database
        if (employeesTable.VerifyLogin(username)) {
            if (password.equals(employeesTable.ViewEmployee(username).get(3))) {
                this.login = true;
                invalidText.setVisible(false);
                
                // If the user is a manager, load the manager window
                if (Integer.parseInt(employeesTable.ViewEmployee(username).get(4)) == 1) {
                    System.out.println("Manager Login");
                    ManagerWindow mW = new ManagerWindow();
                    mW.setVisible(true);
                } else if (Integer.parseInt(employeesTable.ViewEmployee(username).get(4)) == 2) {
                    System.out.println("Server Login");
                    // Server JFrame would now open
                    // Need to create Host and Chef JFrames
                }
            } else {
                invalidText.setText("Invalid Username - Password combination");
                invalidText.setVisible(true);
            }
            setVisible(false);
        } else {
            invalidText.setText("Username not found");
            invalidText.setVisible(true);
        }
                           
    }//GEN-LAST:event_LoginActionViaClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html to
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel invalidText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginText;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
